// Code generated by "stringer -type=CandleResolution"; DO NOT EDIT.

package candles

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CandleOneMinute-0]
	_ = x[CandleFiveMinutes-1]
	_ = x[CandleFifteenMinutes-2]
	_ = x[CandleThirtyMinutes-3]
	_ = x[CandleSixtyMinutes-4]
	_ = x[CandleOneDay-5]
	_ = x[CandleOneWeek-6]
	_ = x[CandleOneMonth-7]
}

const _CandleResolution_name = "CandleOneMinuteCandleFiveMinutesCandleFifteenMinutesCandleThirtyMinutesCandleSixtyMinutesCandleOneDayCandleOneWeekCandleOneMonth"

var _CandleResolution_index = [...]uint8{0, 15, 32, 52, 71, 89, 101, 114, 128}

func (i CandleResolution) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CandleResolution_index)-1 {
		return "CandleResolution(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CandleResolution_name[_CandleResolution_index[idx]:_CandleResolution_index[idx+1]]
}
